<?php

namespace Foysal50x\Tashil\Services;

use Foysal50x\Tashil\Contracts\InvoiceRepositoryInterface;
use Foysal50x\Tashil\Enums\InvoiceStatus;
use Foysal50x\Tashil\Models\Invoice;
use Foysal50x\Tashil\Models\Subscription;
use Illuminate\Support\Str;

class BillingService
{
    public function __construct(
        protected InvoiceRepositoryInterface $invoiceRepo,
    ) {}

    /**
     * Generate an invoice for a subscription.
     */
    public function generateInvoice(Subscription $subscription, ?float $amount = null): Invoice
    {
        $package = $subscription->package;

        return $this->invoiceRepo->create([
            'subscription_id' => $subscription->id,
            // 'invoice_number' is generated by InvoiceObserver
            'amount'          => $amount ?? $package->price,
            'currency'        => $package->currency,
            'status'          => InvoiceStatus::Pending,
            'issued_at'       => now(),
            'due_date'        => now()->addDays(7),
        ]);
    }
}
