<?php

namespace Foysal50x\Tashil\Services;

use Foysal50x\Tashil\Contracts\InvoiceRepositoryInterface;
use Foysal50x\Tashil\Enums\InvoiceKind;
use Foysal50x\Tashil\Enums\InvoiceStatus;
use Foysal50x\Tashil\Models\Invoice;
use Foysal50x\Tashil\Models\Subscription;
use Illuminate\Support\Facades\Config;

class BillingService
{
    public function __construct(
        protected InvoiceRepositoryInterface $invoiceRepo,
    ) {}

    /**
     * Generate a pending invoice for a subscription. `kind` drives how the
     * InvoiceObserver routes the payment (initial → activate, renewal →
     * advance period, proration → no period change). Defaults preserve the
     * pre-existing renewal call site.
     */
    public function generateInvoice(
        Subscription $subscription,
        ?float $amount = null,
        InvoiceKind $kind = InvoiceKind::Renewal,
        ?\DateTimeInterface $periodStart = null,
        ?\DateTimeInterface $periodEnd = null,
        ?int $dueDays = null,
    ): Invoice {
        $package = $subscription->package;
        $dueDays ??= 7;

        return $this->invoiceRepo->create([
            'subscription_id' => $subscription->id,
            // 'invoice_number' is generated by InvoiceObserver
            'kind'         => $kind,
            'amount'       => $amount ?? $package->price,
            'currency'     => $package->currency,
            'status'       => InvoiceStatus::Pending,
            'period_start' => $periodStart,
            'period_end'   => $periodEnd,
            'issued_at'    => now(),
            'due_date'     => now()->addDays($dueDays),
        ]);
    }

    /**
     * Issue the first-period invoice for a freshly-subscribed (pending)
     * plan. Access begins only when this invoice is paid (InvoiceObserver →
     * SubscriptionService::activate). The due window is shorter than a
     * renewal's because a pending subscription has no access yet.
     */
    public function issueInitialInvoice(Subscription $subscription): Invoice
    {
        $dueDays = (int) Config::get('tashil.billing.initial_invoice_due_days', 1);

        return $this->generateInvoice(
            $subscription,
            kind: InvoiceKind::Initial,
            periodStart: now(),
            dueDays: $dueDays,
        );
    }
}
